apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-enricher
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: order-enricher
  template:
    metadata:
      labels:
        app: order-enricher
    spec:
      containers:
        - name: order-enricher
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: ENRICHER_MODE
              value: {{ .Values.env.ENRICHER_MODE | quote }}
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbit-creds
                  key: password
          envFrom:
            - configMapRef:
                name: order-enricher-config
